- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: install python3-apt
  apt:
    name: python3-apt

- name: Ensure apt is set up to work with https sources
  apt:
    name: apt-transport-https

- name: use stable channel
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

- name: update cache
  import_role:
    name: update-apt

- name: install sublime-text
  apt:
    name: sublime-text

- name: install vim
  apt:
    name: vim

- name: Install vscode using snap
  shell: snap install --classic code

- name: install chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
