- name: install docker using snap
  snap:
    name: docker
    classic: yes

- name: create the docker group
  group: 
    name: docker
    state: present

- name: add user to docker group
  user: 
    name: "{{ username }}"
    groups: docker
    append: yes
